### ISSUE TITLE
Updating ruckzuck with ruckzuck oneget closes PowerShell

### ISSUE THREAD

**Issue by MrHappy** [rzander/ruckzuck#62] opened 2019-10-30 08:58 UTC
ruckzuck detects the newer version of itself and tries to update, but doing so closes powershell and so it doesn't update ruckzuck.
Is this behavior by design? 
If so, why not exclude ruckzuck if it doesn't work?
If not, how to fix this?

**Comment by rzander** [comment] 2019-10-30 09:43
You can mark "RuckZuck" and right-click on "edit" to see what it does...
* download new version to %TEMP%\{ContentID}\RuckZuck.exe
* Getthe Path of running RuckZuck.exe
* Kill RuckZuck.exe
* Copy RuckZuck.exe from %TEMP%\{ContentID} to the Path of "old" RuckZuck.exe

It does not automatically start the new version, that's by design... A known Issues is if you have "Controlled Folder Access" enabled and RuckZuck.exe is stored in a protected Path (e.g. Desktop); Then it's not possible to replace the old Version of RuckZuck...

What is the Path of the "old" RuckZuck.exe in your case ? Do you have full access to this path ?

**Comment by MrHappy** [comment] 2019-10-30 10:01
I only use the OneGet-module, not the GUI. If that is what you mean... 😕 
The OneGet-provider tries to update itself and I can't exclude it (I think) and it prevents the automatic update of applications after it.
The only sollution I see at this moment is install de newer version manually.

**Comment by rzander** [comment] 2019-10-30 10:30
Ok, the RuckZuck OneGet Provider  ist a different story...
If you just trigger an `Find-Package -ProviderName RuckZuck -Updates | Install-Package` , then it will try to update the Provider... which can cause issues (have to test that scenario).
But you could use a command like: 
```PowerShell
Find-Package -ProviderName RuckZuck -Updates | ? { $_.PackageFileName -ne 'RuckZuck provider for OneGet' } | Install-Package
```
... to exclude the Provider...

or, you create a list of apps you want to update like:
```PowerShell
        #List of managed Software.
        $ManagedSW = @("7-Zip", "7-Zip(MSI)", "FileZilla", "Google Chrome", "Firefox" , "Notepad++", "Notepad++(x64)", "Code", "AdobeReader DC MUI", "VSTO2010", "GIMP",
            "AdobeReader DC", "Microsoft Power BI Desktop", "Putty", "WinSCP", "AdobeAir", "ShockwavePlayer", "VCRedist2015x64" , "VCRedist2015x86", "VCRedist2017x64" , "VCRedist2017x86",
            "VCRedist2019x64" , "VCRedist2019x86", "VCRedist2013x64", "VCRedist2013x86", "Slack", "Microsoft OneDrive",
            "VCRedist2012x64", "VCRedist2012x86", "VCRedist2010x64" , "VCRedist2010x86", "Office Timeline", "WinRAR", "Viber", "Teams Machine-Wide Installer",
            "VLC", "JavaRuntime8", "JavaRuntime8x64", "FlashPlayerPlugin", "FlashPlayerPPAPI", "Microsoft Azure Information Protection", "KeePass" )

        #Find Software Updates
        $updates = Find-Package -ProviderName RuckZuck -Updates | Select-Object PackageFilename | Sort-Object { Get-Random }

        #Update only managed Software
        $ManagedSW | ForEach-Object { 
            if ($updates.PackageFilename -contains $_) { 
                if ($bLogging) {
                    Write-Log -JSON ([pscustomobject]@{Computer = $env:COMPUTERNAME; EventID = 2000; Description = "RuckZuck updating: $($_)" }) -LogType "DevCDR" 
                }
                "Updating: " + $_ ;
                Install-Package -ProviderName RuckZuck "$($_)" -ea SilentlyContinue
            }
            else { "$($_)" }
        }
```

It's important that you have an updated Version of the OneGet Provider (e.g. V1.7.0.5 is required to update AdobeReaderDC !!).. You can trigger the following command in PowerShell to update the Provider:
```PowerShell
if ((Get-PackageProvider -Name Ruckzuck).Version -lt [version]("1.7.1.0")) {
    &msiexec -i https://github.com/rzander/ruckzuck/releases/download/1.7.1.0/RuckZuck.provider.for.OneGet_x64.msi /qn REBOOT=REALLYSUPPRESS 
}
```

**Comment by MrHappy** [comment] 2019-10-30 10:38
I tried the last line and that closed my powershell also.
After that I ran the msi manually and it asked if I wanted to close PowerShell otherwise a reboot might be required. So I closed PowerShell and afterwards I had the latest version.
It appears that updating RuckZuck OneGet from within PowerShell doesn't work. Probably because the parent process of the msi is closed and thereby the process of the msi is also stopped.

**Comment by rzander** [comment] 2019-10-30 10:52
It does work... But Windows Installer is closing PowerShell as otherwise the Provider DLL is in use... I will check if there is an option to control that behavior...

**Comment by MrHappy** [comment] 2019-10-30 20:18
Thaf is what I did manually.
My conclusion is that you can't update the oneget within powershell when the dll is loaded.
So it's either updating manually or open a powershell-session without the dll loaded.

**Comment by rzander** [comment] 2019-11-02 13:18
Yes, but its not a PowerShell/OneGet/RuckZuck Problem: if WindowsInstaller detect "Files in use", it tries to close the App on Silent installations, with the effect that PowerShell will close... We can now try to modify the MSI, to not close the App but with the result that you have to restart the system so that WindowsInstaller can replace the files during reboot... So I think, we have to live with the effect that PowerShell will close... Do you agree ?

**Comment by MrHappy** [comment] 2019-11-02 14:09
I was not blaming RuckZuck for this behaviour 😉 
It's unfortunate this it doesn't work from within PowerShell, but installing it manually is not a great discomfort.
It would be nice though is RuckZuck OneGet-module would neglect its own update (or just state there is one).

**Comment by rzander** [comment] 2019-11-02 15:12
Manually install means copying the Provider DLL manually, when PowerShell is closed?
Just did a test and `Find-Package -provider RuckZuck -Updates | Install-Package` did update the RuckZuck OneGet Provider...  Of course, PowerShell was automatically closed, but the new version was installed... But, I agree that it's not very nice...

**Comment by MrHappy** [comment] 2019-11-02 16:26
I just installed the most recent msi...

**Comment by rzander** [comment] 2020-03-29 09:18
closed as by design...

**Closed by rzander** 2020-03-29 09:18 UTC
